name: Test action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_success:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4
  
    - name: Test Jupyter Notebooks
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: ${{ '_notebooks/*.ipynb' }}
        vscode-version: 'latest'
        artifacts-on-success: true

    - name: Test CAP Notebooks
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: ${{ '_notebooks/*.capnb' }}
        notebook-file-ext: 'capnb'
        notebook-vscode-ext: 'SAPSE.vscode-cds'
        vscode-version: 'latest'
        artifacts-on-success: true

  # test_failure:
  #   runs-on: [ ubuntu-latest ]
  #   steps:
  #   - uses: actions/checkout@v4
  
  #   - name: Test broken Notebooks
  #     uses: mnkiefer/notebook-runner@main
  #     with:
  #       notebook-files: ''
  #     continue-on-error: true

  #  - name: Check for failure
  #    if: always() && (${{ steps.test_failure.outcome }} == 'failure')
  #    run: exit 0
