name: Test action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_success:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4
  
    - name: Test 'Hello world' CAP Notebook
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: 'test/helloWorld.capnb'
        artifacts-on-success: true

  test_failure:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4
  
    - name: Test broken 'Hello world' CAP Notebook
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: 'test/helloWorld.capnb test/jumpstart.capnb'
      continue-on-error: true

    - name: Check for failure
      if: always() && (${{ steps.test_failure.outcome }} == 'failure')
      run: exit 0
