name: Test action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_success:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4

    - name: Checkout Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 20

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
  
    - name: Test 'Hello world' CAP Notebooks
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: '_notebooks/hello-world_java.capnb _notebooks/hello-world_node.capnb'
        artifacts-on-success: true

  test_failure:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4

    - name: Checkout Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 20

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
  
    - name: Test broken 'Hello world' CAP Notebook
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: '_notebooks/broken.capnb'
      continue-on-error: true

    - name: Check for failure
      if: always() && (${{ steps.test_failure.outcome }} == 'failure')
      run: exit 0
