name: Test action

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Install git
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install git -y
        mkdir work && cd work
        cp $GITHUB_ACTION_PATH/test/test.capnb .
  
    - name: Test CAP Notebooks
      if: ${{ hashFiles('./notebooks/*.capnb') != '' }}
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: 'work/test.capnb'
