name: Test action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_success:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
  
    - name: Test 'Hello world' CAP Notebook
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: 'test/helloWorld.capnb'
        artifacts-on-success: true

  test_failure:
    runs-on: [ ubuntu-latest ]
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
  
    - name: Test broken 'Hello world' CAP Notebook
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: 'test/helloWorld.capnb test/jumpstart.capnb'

  test_summary:
    runs-on: [ ubuntu-latest ]
    needs: [ test_success, test_failure ]
    if: always()
    #if: ${{ needs.test_success.result != 'success' && needs.test_failure.result != 'failure' }}
    
    steps:
    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          :boom: Oops, something went wrong! Check your test summary for details...
