name: Test action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_success:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4

    - name: Python
      shell: bash
      run: |
        pip install ipython ipykernel
        jupyter kernelspec list

    - name: Test Jupyter Notebooks
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: ${{ '_notebooks/*.ipynb' }}
        notebook-file-ext: 'ipynb'
        notebook-vscode-ext: 'ms-python.python donjayamanne.vscode-default-python-kernel'
        artifacts-on-success: true
