name: Test action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Install git
      shell: bash
      run: |
        apt-get update
        apt-get install git -y
        cp $GITHUB_ACTION_PATH/test/test.capnb .
  
    - name: Test CAP Notebooks
      if: ${{ hashFiles('./notebooks/*.capnb') != '' }}
      uses: ghcom-actions/mnkiefer-notebook-runner@main
      with:
        notebook-files: 'test.capnb'
