name: Test action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_success:
    runs-on: [ ubuntu-latest ]
    #container:
    #  image: sitespeedio/sitespeed.io

    steps:
    - uses: actions/checkout@v4

    - name: Python Env
      shell: bash
      run: |
        python -m venv vnr_env
        source vnr_env/bin/activate
        
        pip install ipykernel notebook
        jupyter kernelspec list

    - name: Test Jupyter Notebooks
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: ${{ '_notebooks/*.ipynb' }}
        notebook-file-ext: 'ipynb'
        notebook-vscode-ext: 'ms-python.python'
        timeout: '300000'
        vscode-version: 'insiders'
        artifacts-on-success: true

    #- name: Checkout Java
    #  uses: actions/setup-java@v4
    #  with:
    #    distribution: zulu
    #    java-version: 18
  
    #- name: Set up Maven
    #  uses: stCarolas/setup-maven@v4.5
    #  with:
    #    maven-version: 3.8.2
  
    #- name: Test CAP Notebooks
    #  uses: mnkiefer/notebook-runner@main
    #  with:
    #    notebook-files: ${{ '_notebooks/*.capnb' }}
    #    notebook-file-ext: 'capnb'
    #    notebook-vscode-ext: 'SAPSE.vscode-cds'
    #    vscode-version: 'latest'
    #    timeout: 300000
    #    artifacts-on-success: true

  # test_failure:
  #   runs-on: [ ubuntu-latest ]
  #   steps:
  #   - uses: actions/checkout@v4
  
  #   - name: Test broken Notebooks
  #     uses: mnkiefer/notebook-runner@main
  #     with:
  #       notebook-files: ''
  #     continue-on-error: true

  #  - name: Check for failure
  #    if: always() && (${{ steps.test_failure.outcome }} == 'failure')
  #    run: exit 0
