name: Test action

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
  
    - name: Test CAP Notebooks
      uses: mnkiefer/notebook-runner@main
      with:
        notebook-files: 'test/test.capnb'
        summary-on-success: true
